In [10]:
import numpy as np

arr = np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]])
arr = np.nan_to_num(arr, nan=0)
print(arr)
print(arr.T)

[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [11]:
arr = np.arange(24).reshape(2, 3, 4)
print(np.moveaxis(arr, 0, 2))

[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [12]:
arr = np.array([[1, np.nan, 3], [4, 5, np.nan], [7, 8, 9]], dtype=float)
col_mean = np.nanmean(arr, axis=0)
idx = np.where(np.isnan(arr))
arr[idx] = np.take(col_mean, idx[1])
print(arr)

[[1.  6.5 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [13]:
arr = np.array([[-5, 2, -8], [7, -1, 0]])
arr = np.where(arr < 0, 0, arr)
print(arr)

[[0 2 0]
 [7 0 0]]
