In [9]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6], [7, 8, 9]])

result = np.vstack((arr1, arr2))
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat = arr.flatten()
print(flat)

[1 2 3 4 5 6]


In [11]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1])

[5 4 3 2 1]


In [12]:
arr = np.array([10, 5, 25, 8])
print(arr.max())

arr = np.array([10, 5, 25, 8])
print(arr.min())

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

arr = np.array([[1, 2], [3, 4]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print(arr[i][j])

arr = np.array([[1, 2], [3, 4]])
print(arr[1][0])

arr = np.array([[1, 2, 3], [4, 5, 6]])
s = 0

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        s += arr[i][j]

print(s)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

25
5
(2, 3)
1
2
3
4
3
21
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [13]:
print("using for loop:")
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for i in arr:
    for j in i:
        for k in j:
            print(k)

print("\nusing nditer:")
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

using for loop:
1
2
3
4
5
6
7
8

using nditer:
1
2
3
4
5
6
7
8


In [14]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

avg = (arr1 + arr2) / 2
print(avg)

combined = np.concatenate((arr1.flatten(), arr2.flatten()))

mean = np.mean(combined)
median = np.median(combined)

values, counts = np.unique(combined, return_counts=True)
mode = values[np.argmax(counts)]

print(mean)
print(median)
print(mode)

[[4. 5. 6.]
 [7. 8. 9.]]
6.5
6.5
1
