In [1]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5, 6])
arr2d = arr1d.reshape(2, 3)
print(arr2d)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)

a = np.full((3, 3), 9)
print(a)

b = np.linspace(25, 125, 10)
print(b)

lst = [10, 20, 30, 40]
arr = np.array(lst)
print(arr)

arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1])

arr = np.arange(1, 49).reshape(4, 4, 3)
print(arr[1, 0, -1])

arr = np.arange(1, 17).reshape(4, 4)
print(arr[1::2, ::2])

arr = np.arange(1, 49).reshape(4, 4, 3)
print(arr[1, :2, :2])

arr = np.array([[23, 56, 78, 93], [71, 82, 13, 24]])
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 != 0:
            arr[i][j] = -1
print(arr)

arr = np.array([1, 0, 2, 0, 3, 0, 4])
print(np.nonzero(arr))

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(arr1 * arr2)

arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])
print(np.dot(arr1, arr2))

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64
8
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]
[10 20 30 40]
[5 4 3 2 1]
15
[[ 5  7]
 [13 15]]
[[13 14]
 [16 17]]
[[-1 56 78 -1]
 [-1 82 -1 24]]
(array([0, 2, 4, 6]),)
[5 7 9]
[ 4 10 18]
1875
